# Generated by Django 3.1.7 on 2021-03-30 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_bookings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Chattings',
        ),
    ]
