# Generated by Django 3.1.7 on 2021-03-30 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210331_0205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chattings',
            old_name='text',
            new_name='message',
        ),
    ]
